### ISSUE TITLE
Add support for dragging-and-dropping objects from Final Cut Pro Browser (via FCPXML)

### ISSUE THREAD

**Issue by samplue** [latenitefilms/RecallToolbox#1]
Would love to see the ability to drag and drop timelines, events, clips or titles directly into a folder instead of copy-pasting them. Support for fcpxml to quickly share assets would be a welcome addition

**Comment by latenitefilms** [comment]
This is a great idea! Will investigate.

**Comment by latenitefilms** [comment]
This will be added in the next build.
