### ISSUE TITLE
User Interface Improvements

### ISSUE THREAD

**Issue by latenitefilms** [latenitefilms/RecallToolbox#4]
Marc Bach writes:

> Hey just sent you some feedback for the recall toolbox and I wanted to add more:
> 
> The Sharing Info and Accept Share buttons should be only Share and Join or something similar. Also when sharing a folder, I think the sharing floating window should have a cancel button or a commit kind of button so you can scrap all at once. And permissions should be set at that moment of adding the email address, the way it is now you add the address and then you have to go back and change permissions to read or write.
> 
> Also I see a double click pastes the item on the timeline but what if I just want to “read” the effects to copy to the clipboard to paste them as attributes? Should that be a single click, right click, a separate “copy to clipboard” button?

**Comment by latenitefilms** [comment]
Marc Bach writes:

> Hey Chris, I think this could be a cleaner more intuitive look for the buttons
> 
> ![](https://github.com/latenitefilms/RecallToolbox/assets/22286696/bb4bbd03-841b-443f-8655-fb84bea4266a)

**Comment by latenitefilms** [comment]
The user interface has been improved.

**Comment by florian-duffe** [comment]
Chris wrote in FCP-WFG: "it gets complicated when you can hide the sidebar."
my suggestion: why not move "remove folder" and "remove item" into the right click context menu of the respective items. Additionally: enable removing with select and hit "delete" key. 
Then just have a big + sign at the bottom or the top of the folder list and the items window. 
Compare MacOS contacts app: New list is a hiding + in a circle at the top, new card is a big + at the bottom of the active card.
I guess they aren't consistent there either. I would go for a big visible + sign.
